# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: cibuilds/hugo:latest

    working_directory: ~/hugo
    environment:
      HUGO_BUILD_DIR: ~/hugo/public

    steps:
      # install stuffs
      - run: apk update && apk add git lftp
      - run: lftp --version

      # checkout the repo
      - checkout

      - run: hugo version
      - run: HUGO_ENV=production hugo -v

      - deploy:
          name: "Deploy via FTPS"
          command: lftp -e "set ftp:ssl-auth TLS;set ftp:ssl-force true;set ftp:ssl-protect-data true;mirror -R $HUGO_BUILD_DIR $FTP_DIR;bye" -u $FTP_USER,$FTP_PASS $FTP_HOST
